[2024-07-30T19:35:04.245+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-30T19:35:04.263+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: zillow-analytics-dag.tsk_extract_zillow_data_var manual__2024-07-30T19:34:25.193812+00:00 [queued]>
[2024-07-30T19:35:04.269+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: zillow-analytics-dag.tsk_extract_zillow_data_var manual__2024-07-30T19:34:25.193812+00:00 [queued]>
[2024-07-30T19:35:04.269+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2024-07-30T19:35:04.285+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): tsk_extract_zillow_data_var> on 2024-07-30 19:34:25.193812+00:00
[2024-07-30T19:35:04.289+0000] {standard_task_runner.py:64} INFO - Started process 1864 to run task
[2024-07-30T19:35:04.292+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'zillow-analytics-dag', 'tsk_extract_zillow_data_var', 'manual__2024-07-30T19:34:25.193812+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/zillowanalytics.py', '--cfg-path', '/tmp/tmpijo8714e']
[2024-07-30T19:35:04.293+0000] {standard_task_runner.py:91} INFO - Job 17: Subtask tsk_extract_zillow_data_var
[2024-07-30T19:35:04.328+0000] {task_command.py:426} INFO - Running <TaskInstance: zillow-analytics-dag.tsk_extract_zillow_data_var manual__2024-07-30T19:34:25.193812+00:00 [running]> on host ip-172-31-16-43.eu-central-1.compute.internal
[2024-07-30T19:35:04.402+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='yashvij1996@gmail.com' AIRFLOW_CTX_DAG_OWNER='Yash-First-Airflow-DAG' AIRFLOW_CTX_DAG_ID='zillow-analytics-dag' AIRFLOW_CTX_TASK_ID='tsk_extract_zillow_data_var' AIRFLOW_CTX_EXECUTION_DATE='2024-07-30T19:34:25.193812+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-30T19:34:25.193812+00:00'
[2024-07-30T19:35:04.403+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-30T19:35:05.231+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-30T19:35:05.231+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/zillowdata_de_youtube_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airflow/dags/zillowanalytics.py", line 33, in extract_zillow_data
    with open(output_file_path, "w") as output_file :
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/json_output/response_data_30072024193504.json'
[2024-07-30T19:35:05.236+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=zillow-analytics-dag, task_id=tsk_extract_zillow_data_var, run_id=manual__2024-07-30T19:34:25.193812+00:00, execution_date=20240730T193425, start_date=20240730T193504, end_date=20240730T193505
[2024-07-30T19:35:05.249+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 17 for task tsk_extract_zillow_data_var ([Errno 2] No such file or directory: '/home/ubuntu/json_output/response_data_30072024193504.json'; 1864)
[2024-07-30T19:35:05.266+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-30T19:35:05.277+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-30T19:35:05.278+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
